"""week 4 chat history conversations llm usage

Revision ID: 329137d9c02e
Revises: 3924e6aa3ba6
Create Date: 2026-08-12 01:53:02.437503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329137d9c02e'
down_revision: Union[str, Sequence[str], None] = '3924e6aa3ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_chat_history_conversation_id_conversations'), 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_history_conversation_id_conversations'), type_='foreignkey')

    # ### end Alembic commands ###
