"""week 3 document pipeline

Revision ID: 3924e6aa3ba6
Revises: aa7c76be300d
Create Date: 2026-08-06 00:03:19.552424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3924e6aa3ba6'
down_revision: Union[str, Sequence[str], None] = 'aa7c76be300d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('vector_id', sa.String(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('file_hash', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('pdf_title', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('pdf_author', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('is_encrypted', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='processingstatus'), nullable=False))
    op.add_column('documents', sa.Column('processing_error', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'processing_error')
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'is_encrypted')
    op.drop_column('documents', 'pdf_author')
    op.drop_column('documents', 'pdf_title')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'file_hash')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
