"""Add document_id to policy_versions

Revision ID: a96e75385677
Revises: e62e2562990e
Create Date: 2026-08-13 00:01:18.100525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96e75385677'
down_revision: Union[str, Sequence[str], None] = 'e62e2562990e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_policy_versions_document_id_documents'), 'documents', ['document_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_policy_versions_document_id_documents'), type_='foreignkey')
        batch_op.drop_column('document_id')

    # ### end Alembic commands ###
