"""Add analysis tables

Revision ID: cbbaed2a0ffc
Revises: 329137d9c02e
Create Date: 2026-08-12 23:29:16.830825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbbaed2a0ffc'
down_revision: Union[str, Sequence[str], None] = '329137d9c02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_analysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'analyzing', 'completed', 'failed', name='analysisstatus'), nullable=False),
    sa.Column('executive_summary', sa.String(), nullable=True),
    sa.Column('key_parties', sa.JSON(), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_analysis_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_analysis'))
    )
    op.create_table('analysis_clauses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('important_clause', 'vendor_obligation', 'payment_terms', 'termination', 'confidentiality', 'data_protection', 'liability', 'dispute_resolution', name='clausecategory'), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('summary_text', sa.String(), nullable=True),
    sa.Column('source_chunk_id', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['document_analysis.id'], name=op.f('fk_analysis_clauses_analysis_id_document_analysis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], name=op.f('fk_analysis_clauses_source_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_clauses'))
    )
    op.create_table('risks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('high', 'medium', 'low', name='riskseverity'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('source_chunk_id', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['document_analysis.id'], name=op.f('fk_risks_analysis_id_document_analysis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], name=op.f('fk_risks_source_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risks'))
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('related_risk_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['document_analysis.id'], name=op.f('fk_recommendations_analysis_id_document_analysis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_risk_id'], ['risks.id'], name=op.f('fk_recommendations_related_risk_id_risks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('risks')
    op.drop_table('analysis_clauses')
    op.drop_table('document_analysis')
    # ### end Alembic commands ###
