"""Add compliance and policy versions

Revision ID: e62e2562990e
Revises: cbbaed2a0ffc
Create Date: 2026-08-12 23:58:35.690992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62e2562990e'
down_revision: Union[str, Sequence[str], None] = 'cbbaed2a0ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.Column('processing_status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='processingstatus'), nullable=False),
    sa.Column('processing_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_versions_policy_id_policies')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_policy_versions_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_versions'))
    )
    op.create_table('compliance_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('policy_version_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'comparing', 'completed', 'failed', name='compliancestatus'), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_compliance_results_document_id_documents')),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_compliance_results_policy_id_policies')),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_compliance_results_policy_version_id_policy_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_results'))
    )
    op.create_table('policy_requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_version_id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('payment_terms', 'confidentiality', 'data_protection', 'liability', 'termination', 'dispute_resolution', 'vendor_obligation', 'important_clause', name='clausecategory'), nullable=False),
    sa.Column('requirement_text', sa.String(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('source_chunk_id', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_policy_requirements_policy_version_id_policy_versions')),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], name=op.f('fk_policy_requirements_source_chunk_id_document_chunks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_requirements'))
    )
    op.create_table('compliance_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('compliance_result_id', sa.String(), nullable=False),
    sa.Column('finding_type', sa.Enum('missing_clause', 'weak_clause', 'conflicting_clause', 'policy_violation', name='findingtype'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('high', 'medium', 'low', name='riskseverity'), nullable=False),
    sa.Column('policy_requirement_id', sa.String(), nullable=True),
    sa.Column('contract_source_chunk_id', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compliance_result_id'], ['compliance_results.id'], name=op.f('fk_compliance_findings_compliance_result_id_compliance_results')),
    sa.ForeignKeyConstraint(['contract_source_chunk_id'], ['document_chunks.id'], name=op.f('fk_compliance_findings_contract_source_chunk_id_document_chunks')),
    sa.ForeignKeyConstraint(['policy_requirement_id'], ['policy_requirements.id'], name=op.f('fk_compliance_findings_policy_requirement_id_policy_requirements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_findings'))
    )
    op.create_table('compliance_suggestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('compliance_result_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['compliance_result_id'], ['compliance_results.id'], name=op.f('fk_compliance_suggestions_compliance_result_id_compliance_results')),
    sa.ForeignKeyConstraint(['finding_id'], ['compliance_findings.id'], name=op.f('fk_compliance_suggestions_finding_id_compliance_findings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_suggestions'))
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_column('current_version')

    op.drop_table('compliance_suggestions')
    op.drop_table('compliance_findings')
    op.drop_table('policy_requirements')
    op.drop_table('compliance_results')
    op.drop_table('policy_versions')
    # ### end Alembic commands ###
